name: retail-v1-deploy-mvn

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/api-retail-mvn.yaml'
      - 'retail-v1/**'
  workflow_dispatch:

jobs:
  build:
    name: "Deploy To Apigee"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SECRET_V1}}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: bearer token
        env:
         ENV: "eval"
        run: echo "$ENV"
      - name: Create API bundle
        run: mvn install -f ./retail-v1/pom.xml -ntp -Pdev -Dbearer=$(gcloud auth print-access-token) -Dfile=$GOOGLE_APPLICATION_CREDENTIALS -Denv=$ENV -Dorg=${{secrets.APIGEE_ORG_V1}} 
