name: retail-v1-deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/api-retail.yaml'
      - 'retail-v1/**'
  workflow_dispatch:

jobs:
  build:
    name: "Deploy To Apigee"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SECRET}}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: env variables
        env:
         ENV: "eval"
        run: echo "$ENV"
      - name: Create API bundle
        id: create
        run: mvn -f ./retail-v1/pom.xml -ntp process-resources apigee-enterprise:configure -Pdev -Dorg=${{secrets.APIGEE_ORG}} -Denv=$ENV
      - name: Upload API Proxy Bundle
        id: upload
        run: mvn -f ./retail-v1/pom.xml -X -ntp apigee-enterprise:deploy -Pdev -Dorg=${{secrets.APIGEE_ORG}} -Denv=$ENV -Dfile=$GOOGLE_APPLICATION_CREDENTIALS
        
